# Generated by Django 2.2.1 on 2019-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190613_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='users.Interest'),
        ),
    ]
