# Generated by Django 2.2.1 on 2019-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190617_0849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='interests.Interest'),
        ),
    ]
