# Generated by Django 2.2.1 on 2019-06-20 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('users', '0005_auto_20190617_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('interests', models.ManyToManyField(blank=True, to='interests.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='FriendCircleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(blank=True)),
                ('friendcircle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FriendCircle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
