# Generated by Django 2.2.1 on 2019-06-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friendcircle_friendcirclemembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendcirclemembership',
            unique_together={('user', 'friendcircle')},
        ),
    ]
