# Generated by Django 2.2.1 on 2019-06-21 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190620_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='_customuser_liked_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
