# Generated by Django 2.2.1 on 2019-06-24 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='_customuser_liked_+', to='users.FriendCircle'),
        ),
        migrations.CreateModel(
            name='FriendCircleMatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_match_status', models.CharField(choices=[('O', 'Not swiped'), ('V', 'Swiped Right'), ('X', 'Swiped Left')], default='O', max_length=1)),
                ('friendcircle_match_status', models.CharField(choices=[('O', 'Not swiped'), ('V', 'Swiped Right'), ('X', 'Swiped Left')], default='O', max_length=1)),
                ('friendcircle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FriendCircle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'friendcircle')},
            },
        ),
    ]
