# Generated by Django 2.2.1 on 2019-06-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190624_0847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendcirclematcher',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendcirclematcher',
            name='friendcircle',
        ),
        migrations.RemoveField(
            model_name='friendcirclematcher',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='friendcirclemembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendcirclemembership',
            name='friendcircle',
        ),
        migrations.RemoveField(
            model_name='friendcirclemembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='liked',
        ),
        migrations.DeleteModel(
            name='FriendCircle',
        ),
        migrations.DeleteModel(
            name='FriendCircleMatcher',
        ),
        migrations.DeleteModel(
            name='FriendCircleMembership',
        ),
    ]
