# Generated by Django 2.2.1 on 2019-06-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrikmuurPost',
        ),
    ]
