# Generated by Django 2.2.1 on 2019-06-12 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prikmuur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prikmuurpost', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prikmuurpost', to=settings.AUTH_USER_MODEL),
        ),
    ]
