# Generated by Django 2.2.1 on 2019-06-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prikmuur', '0002_auto_20190612_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='je moeder', max_length=45),
            preserve_default=False,
        ),
    ]
