# Generated by Django 2.2.1 on 2019-06-20 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20190620_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendCircleMatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_match_status', models.CharField(choices=[('O', 'Not swiped'), ('V', 'Swiped Right'), ('X', 'Swiped Left')], default='O', max_length=1)),
                ('friendcircle_match_status', models.CharField(choices=[('O', 'Not swiped'), ('V', 'Swiped Right'), ('X', 'Swiped Left')], default='O', max_length=1)),
                ('friendcircle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FriendCircle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'friendcircle')},
            },
        ),
    ]
