# Generated by Django 2.2.1 on 2019-06-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FriendCircleMatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_match_status', models.CharField(choices=[('O', 'Not swiped'), ('V', 'Swiped Right'), ('X', 'Swiped Left')], default='O', max_length=1)),
                ('friendcircle_match_status', models.CharField(choices=[('O', 'Not swiped'), ('V', 'Swiped Right'), ('X', 'Swiped Left')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FriendCircleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(blank=True)),
                ('friendcircle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendcircle.FriendCircle')),
            ],
        ),
    ]
