# Generated by Django 2.2.1 on 2019-07-01 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('interests', models.ManyToManyField(blank=True, to='interests.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='FriendCircleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('friendcircle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendcircle.FriendCircle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'friendcircle')},
            },
        ),
        migrations.CreateModel(
            name='FriendCircleMatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_match_status', models.CharField(choices=[('O', 'Not swiped'), ('V', 'Swiped Right'), ('X', 'Swiped Left')], default='O', max_length=1)),
                ('friendcircle_match_status', models.CharField(choices=[('O', 'Not swiped'), ('V', 'Swiped Right'), ('X', 'Swiped Left')], default='O', max_length=1)),
                ('friendcircle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendcircle.FriendCircle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'friendcircle')},
            },
        ),
    ]
