# Generated by Django 2.2.1 on 2019-06-26 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friendcircle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendcirclemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendcirclematcher',
            name='friendcircle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendcircle.FriendCircle'),
        ),
        migrations.AddField(
            model_name='friendcirclematcher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendcircle',
            name='interests',
            field=models.ManyToManyField(blank=True, to='interests.Interest'),
        ),
        migrations.AlterUniqueTogether(
            name='friendcirclemembership',
            unique_together={('user', 'friendcircle')},
        ),
        migrations.AlterUniqueTogether(
            name='friendcirclematcher',
            unique_together={('user', 'friendcircle')},
        ),
    ]
