# Generated by Django 2.2.1 on 2019-07-01 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendcircle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendcirclemembership',
            name='friendcircle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendcirclememberships', to='friendcircle.FriendCircle'),
        ),
        migrations.AlterField(
            model_name='friendcirclemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendcirclememberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
