# Generated by Django 2.2.1 on 2019-07-01 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendcircle', '0002_auto_20190701_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendcircle',
            name='members',
            field=models.ManyToManyField(through='friendcircle.FriendCircleMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
