# Generated by Django 2.2.1 on 2019-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendcircle', '0002_auto_20190626_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendcirclemembership',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
